import {
  ALLOWED_IMPLEMENTATION_TYPES,
  ALLOWED_SIZE_NAMES,
  ALLOWED_STATUSES,
  ALLOWED_ENVIRONMENTS,
  ALLOWED_REGIONS,
} from '../../data/serverDataSheet.js';

export const SHEET_GROUPS = [
  {
    id: 'group-1',
    name: 'GROUP 1 — CUSTOMER & VERSION',
    colorClass: 'bg-[#004B87] text-white',
    colSpan: 12,
  },
  {
    id: 'group-2',
    name: 'GROUP 2 — SERVER DETAILS',
    colorClass: 'bg-[#006688] text-white',
    colSpan: 7,
  },
  {
    id: 'group-3',
    name: 'GROUP 3 — DATABASE ACCOUNTS',
    colorClass: 'bg-[#1E3A8A] text-white',
    colSpan: 3,
  },
  {
    id: 'group-4',
    name: 'GROUP 4 — GMSA ACCOUNTS',
    colorClass: 'bg-[#0E7490] text-white',
    colSpan: 1,
  },
  {
    id: 'group-5',
    name: 'GROUP 5 — SFTP',
    colorClass: 'bg-[#312E81] text-white',
    colSpan: 2,
  },
  {
    id: 'group-6',
    name: 'GROUP 6 — URLS',
    colorClass: 'bg-[#0369A1] text-white',
    colSpan: 10,
  },
  {
    id: 'group-7',
    name: 'GROUP 7 — APPLICATIONS INSTALLED ON SERVERS',
    colorClass: 'bg-[#1E40AF] text-white',
    colSpan: 6,
  },
];

export const SHEET_COLUMNS = [
  // ==========================================
  // GROUP 1: CUSTOMER & VERSION (12 Columns)
  // ==========================================
  {
    key: 'customerName',
    label: 'Customer Name',
    group: 'group-1',
    width: 170,
    minWidth: 140,
    type: 'text',
    frozen: true,
  },
  {
    key: 'customerCode',
    label: 'Customer Code',
    group: 'group-1',
    width: 130,
    minWidth: 110,
    type: 'text',
    isMonospace: true,
    frozen: true,
  },
  {
    key: 'jpowerId',
    label: 'JPower ID',
    group: 'group-1',
    width: 180,
    minWidth: 150,
    type: 'text',
    isMonospace: true,
    frozen: true,
  },
  {
    key: 'primarySme',
    label: 'Onboarding SME - Primary',
    group: 'group-1',
    width: 180,
    minWidth: 150,
    type: 'text',
  },
  {
    key: 'secondarySme',
    label: 'Onboarding SME - Secondary',
    group: 'group-1',
    width: 185,
    minWidth: 150,
    type: 'text',
  },
  {
    key: 'implementationType',
    label: 'Implementation Type',
    group: 'group-1',
    width: 165,
    minWidth: 140,
    type: 'dropdown',
    options: ALLOWED_IMPLEMENTATION_TYPES,
  },
  {
    key: 'sizeName',
    label: 'Size Name',
    group: 'group-1',
    width: 125,
    minWidth: 110,
    type: 'dropdown',
    options: ALLOWED_SIZE_NAMES,
  },
  {
    key: 'status',
    label: 'Status',
    group: 'group-1',
    width: 125,
    minWidth: 105,
    type: 'dropdown',
    options: ALLOWED_STATUSES,
  },
  {
    key: 'mscDss',
    label: 'MSC / DSS',
    group: 'group-1',
    width: 120,
    minWidth: 100,
    type: 'dropdown',
    options: ['MSC', 'DSS', 'MSC + DSS'],
  },
  {
    key: 'cloudRegion',
    label: 'Cloud Region',
    group: 'group-1',
    width: 135,
    minWidth: 120,
    type: 'dropdown',
    options: ALLOWED_REGIONS,
  },
  {
    key: 'version',
    label: 'Version',
    group: 'group-1',
    width: 110,
    minWidth: 95,
    type: 'text',
    isMonospace: true,
  },
  {
    key: 'environment',
    label: 'Environment',
    group: 'group-1',
    width: 120,
    minWidth: 105,
    type: 'dropdown',
    options: ALLOWED_ENVIRONMENTS,
    isBadge: true,
  },

  // ==========================================
  // GROUP 2: SERVER DETAILS (7 Columns)
  // ==========================================
  {
    key: 'citrixServer',
    label: 'Citrix Server',
    group: 'group-2',
    width: 210,
    minWidth: 160,
    type: 'text',
    isMonospace: true,
  },
  {
    key: 'utilityServer',
    label: 'Utility Server',
    group: 'group-2',
    width: 210,
    minWidth: 160,
    type: 'text',
    isMonospace: true,
  },
  {
    key: 'dbServerName',
    label: 'DB Server Name',
    group: 'group-2',
    width: 240,
    minWidth: 180,
    type: 'text',
    isMonospace: true,
  },
  {
    key: 'vsCitrix',
    label: 'VS Citrix',
    group: 'group-2',
    width: 190,
    minWidth: 140,
    type: 'text',
    isMonospace: true,
  },
  {
    key: 'reportingServer',
    label: 'Reporting Server',
    group: 'group-2',
    width: 200,
    minWidth: 150,
    type: 'text',
    isMonospace: true,
  },
  {
    key: 'channelClusteringServer',
    label: 'Channel Clustering Server',
    group: 'group-2',
    width: 210,
    minWidth: 160,
    type: 'text',
    isMonospace: true,
  },
  {
    key: 'daasServer',
    label: 'DAAS Server',
    group: 'group-2',
    width: 190,
    minWidth: 140,
    type: 'text',
    isMonospace: true,
  },

  // ==========================================
  // GROUP 3: DATABASE ACCOUNTS (3 Columns)
  // ==========================================
  {
    key: 'databaseName',
    label: 'Database Name',
    group: 'group-3',
    width: 190,
    minWidth: 150,
    type: 'text',
    isMonospace: true,
  },
  {
    key: 'dbKeyVaultName',
    label: 'DB Key Vault Name',
    group: 'group-3',
    width: 190,
    minWidth: 150,
    type: 'text',
    isMonospace: true,
  },
  {
    key: 'storageAccountKeyVaultName',
    label: 'Storage Account Key Vault Name',
    group: 'group-3',
    width: 220,
    minWidth: 170,
    type: 'text',
    isMonospace: true,
  },

  // ==========================================
  // GROUP 4: GMSA ACCOUNTS (1 Column)
  // ==========================================
  {
    key: 'gmsaAccountName',
    label: 'GMSA Account Name',
    group: 'group-4',
    width: 190,
    minWidth: 150,
    type: 'text',
    isMonospace: true,
  },

  // ==========================================
  // GROUP 5: SFTP (2 Columns)
  // ==========================================
  {
    key: 'sftpUserName',
    label: 'SFTP User Name',
    group: 'group-5',
    width: 180,
    minWidth: 140,
    type: 'text',
    isMonospace: true,
  },
  {
    key: 'sftpGateway',
    label: 'SFTP Gateway',
    group: 'group-5',
    width: 230,
    minWidth: 170,
    type: 'text',
    isMonospace: true,
  },

  // ==========================================
  // GROUP 6: URLS (10 Columns)
  // ==========================================
  {
    key: 'realm',
    label: 'Realm',
    group: 'group-6',
    width: 180,
    minWidth: 140,
    type: 'text',
    isMonospace: true,
  },
  {
    key: 'citrixUrl',
    label: 'Citrix URL',
    group: 'group-6',
    width: 240,
    minWidth: 180,
    type: 'url',
    isMonospace: true,
  },
  {
    key: 'luminatePortalUrl',
    label: 'Luminate Portal URL',
    group: 'group-6',
    width: 240,
    minWidth: 180,
    type: 'url',
    isMonospace: true,
  },
  {
    key: 'directOpenAccessUrl',
    label: 'Direct Open Access URL',
    group: 'group-6',
    width: 260,
    minWidth: 190,
    type: 'url',
    isMonospace: true,
  },
  {
    key: 'contentServiceUrl',
    label: 'Content Service URL',
    group: 'group-6',
    width: 250,
    minWidth: 180,
    type: 'url',
    isMonospace: true,
  },
  {
    key: 'imageServerUrl',
    label: 'Image Server URL',
    group: 'group-6',
    width: 250,
    minWidth: 180,
    type: 'url',
    isMonospace: true,
  },
  {
    key: 'zabbixUrl',
    label: 'Zabbix URL',
    group: 'group-6',
    width: 250,
    minWidth: 180,
    type: 'url',
    isMonospace: true,
  },
  {
    key: 'directSpacePlanningWebUrl',
    label: 'Direct Space Planning Web URL',
    group: 'group-6',
    width: 260,
    minWidth: 190,
    type: 'url',
    isMonospace: true,
  },
  {
    key: 'directStrategicAssortmentUrl',
    label: 'Direct Strategic Assortment URL',
    group: 'group-6',
    width: 260,
    minWidth: 190,
    type: 'url',
    isMonospace: true,
  },
  {
    key: 'directStrategicSpaceUrl',
    label: 'Direct Strategic Space URL',
    group: 'group-6',
    width: 260,
    minWidth: 190,
    type: 'url',
    isMonospace: true,
  },

  // ==========================================
  // GROUP 7: APPLICATIONS INSTALLED ON SERVERS (6 Columns)
  // ==========================================
  {
    key: 'citrixServerApps',
    label: 'Citrix Server Applications',
    group: 'group-7',
    width: 280,
    minWidth: 200,
    type: 'multiline',
  },
  {
    key: 'vsCitrixApps',
    label: 'VS Citrix Applications',
    group: 'group-7',
    width: 240,
    minWidth: 180,
    type: 'multiline',
  },
  {
    key: 'utilityServerApps',
    label: 'Utility Server Applications',
    group: 'group-7',
    width: 280,
    minWidth: 200,
    type: 'multiline',
  },
  {
    key: 'reportingServerApps',
    label: 'Reporting Server Applications',
    group: 'group-7',
    width: 270,
    minWidth: 190,
    type: 'multiline',
  },
  {
    key: 'dbServerApps',
    label: 'DB Server Applications',
    group: 'group-7',
    width: 270,
    minWidth: 190,
    type: 'multiline',
  },
  {
    key: 'thirdPartyApps',
    label: 'Third Party Applications',
    group: 'group-7',
    width: 270,
    minWidth: 190,
    type: 'multiline',
  },
];
